all:
	clang++ -std=c++17 -ggdb3 -Weverything -Wno-float-equal -Wno-newline-eof -Wno-c++98-compat -Wno-c++98-compat-pedantic -I./include source/*.cpp core/main.cpp -o ./app/main

test:
	clang++ -std=c++17 -ggdb3 -Weverything -Wno-float-equal -Wno-newline-eof -Wno-c++98-compat -Wno-c++98-compat-pedantic -I./include source/*.cpp core/test.cpp -o ./app/test